import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import { bellefair, barlowCondensed, barlow } from "../../public/fonts/page"; // Adjust the import path as necessary

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bellefair.className} ${barlowCondensed.className} ${barlow.className} antialiased max-w-screen-2xl`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
